### ISSUE TITLE
soaplib version 2.0.0

### ISSUE THREAD

**Issue by dany0792** [MircoT/flask-soap-server#3]
It is important to install soaplib version 2.0.0-beta2 !!! (first, you should uninstall previous version of it)

**Comment by MircoT** [comment]
This depends on your python environment. Of course, is better to have a virtual env during the development, otherwise you can occur in dependency problem like that. 

But I don't want to take care so much about this library that is discontinued and probably I will update the example to the new one like [spyne.io](http://spyne.io/)
